### ISSUE TITLE
Responsive Design: Immediate buffering of Vimeo videos

### ISSUE THREAD

**Issue by ronvoluted** [ForJournalism/fj-responsive-design#1]
Embedded videos on page (15 or so of them) all begin to buffer immediately on page load.

**Comment by gotoplanb** [comment]
Yup, this is definitely in the backlog. On one hand currently you get everything prebuffered. Conversely, it crushed your connection if on mobile data.

We'll try get this fix next week of having thumbnail images swap for video player on click/touch.

**Comment by ronvoluted** [comment]
Strange, you would think the API would have parameters letting you change that instead of needing some workaround. Come to think of it, Vimeo embeds usually buffer only once you hit play- seems like something or another is overriding the default.

**Comment by gotoplanb** [comment]
We're not using a direct Vimeo embed. There's a translation from an URL into a popcorn.js player. This is so we can load videos from Vimeo, YouTube, S3 or wherever.

**Comment by ronvoluted** [comment]
Ah, that explains things. Well I guess the plus-side of using a thumbnail is having a bit more control.

Thanks for making this a priority and congratulations again on the team's progress so far.

**Comment by gotoplanb** [comment]
Yup, it's going to take a while to get the design and collaboration tools out the door, but it made sense to just ship the raw content now. Lots more planned. Thank you for your support.
