### ISSUE TITLE
Videos don't play in Firefox 24 or Android Firefox 'Nightly'

### ISSUE THREAD

**Issue by znmeb** [ForJournalism/fj-responsive-design#3]
When I open the course in Firefox, either Linux Firefox 24 or Android Firefox 'Nightly', all I see is a _text_ Vimeo link. They do show up and play in both desktop and Android Chrome browsers.

**Comment by gotoplanb** [comment]
Yep yep. Overall Firefox issue with out popcorn.js implementation.

**Comment by znmeb** [comment]
I know a few folks at Mozilla - perhaps I can file a bug over there. Firefox ought to be able to handle this stuff without whining.

**Comment by gotoplanb** [comment]
Probably not a popcorn.js issue itself. The Publet folks already have this
tickets for the next sprint.
